[package]
name = "papaya"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic-wait = "1.1.0"
seize = "0.4.4"

[dev-dependencies]
rand = "0.8.5"
base64 = "0.22.1"
hdrhistogram = "7.5.4"
dashmap = "5.5.3"
criterion = "0.5.1"
tokio = { version = "1.38.0", features = ["fs", "rt"] }

[[bench]]
name = "single_thread"
harness = false

[[bench]]
name = "latency"
harness = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(papaya_stress)', 'cfg(papaya_asan)'] }
